### ISSUE TITLE
Unexpected panic after running for approximately 2 days

### ISSUE THREAD

**Issue by dankgrinder** [dankgrinder/dankgrinder#13]
**Expected behavior**
The program to not panic

**Actual behavior**
The program panicked

**Steps to reproduce**
Run for approximately 2 days. 50 instances are run at the same time. May or may not affect this problem.

**Logs**
```
panic: send on closed channel

goroutine 35324892 [running]:
github.com/dankgrinder/dankgrinder/scheduler.(*Scheduler).ResumeWithCommandOrPrioritySchedule(...)
	/hgo/src/github.com/dankgrinder/dankgrinder/scheduler/scheduler.go:172
github.com/dankgrinder/dankgrinder/responder.(*Responder).hl(0xc00049b380, 0xc000b6ee60, 0x12, 0xc000b6eee0, 0x12, 0xc000b6ef40, 0x12, 0xc000b6ef00, 0x12, 0xc001377d64, ...)
	/go/src/github.com/dankgrinder/dankgrinder/responder/router.go:97 +0x2b4
github.com/dankgrinder/dankgrinder/discord.(*MessageRouter).process(0xc001a9f8f0, 0xc000b6ee60, 0x12, 0xc000b6eee0, 0x12, 0xc000b6ef40, 0x12, 0xc000b6ef00, 0x12, 0xc001377d64, ...)
	/go/src/github.com/dankgrinder/dankgrinder/discord/router.go:35 +0x1a2
created by github.com/dankgrinder/dankgrinder/discord.(*WSConn).listen
	/go/src/github.com/dankgrinder/dankgrinder/discord/websocket.go:132 +0x230
```

```
panic: send on closed channel

goroutine 18004094 [running]:
github.com/dankgrinder/dankgrinder/scheduler.(*Scheduler).ResumeWithCommandOrPrioritySchedule(...)
	/go/src/github.com/dankgrinder/dankgrinder/scheduler/scheduler.go:172
github.com/dankgrinder/dankgrinder/responder.(*Responder).search(0xc00040bec0, 0xc00012ebe0, 0x12, 0xc00012ec20, 0x12, 0xc00012ece0, 0x12, 0xc00012ec60, 0x12, 0xc0001c6784, ...)
	/go/src/github.com/dankgrinder/dankgrinder/responder/router.go:69 +0x32b
github.com/dankgrinder/dankgrinder/discord.(*MessageRouter).process(0xc001153350, 0xc00012ebe0, 0x12, 0xc00012ec20, 0x12, 0xc00012ece0, 0x12, 0xc00012ec60, 0x12, 0xc0001c6784, ...)
	/go/src/github.com/dankgrinder/dankgrinder/discord/router.go:35 +0x1a2
created by github.com/dankgrinder/dankgrinder/discord.(*WSConn).listen
	/go/src/github.com/dankgrinder/dankgrinder/discord/websocket.go:132 +0x230
```

**Environment**
OS: Ubuntu 20.04
Dank Grinder version: 0.8.0
Config: not relevant

**Comment by dankgrinder** [comment]
Guess we'll find out in 2 days if it's fixed

**Comment by 1x6** [comment]
i think that just means you lost connection
